version: '2'
services:

    app:
        build: .
        image: cr.yandex/${registry_id}/russky-app-2022:{docker-tag} # TODO registry id
        ports:
            - "8080:8080"
        environment:
            - ELASTIC_APM_SERVICE_NAME=russky-app-2022
            - ELASTIC_APM_SERVER_URL=http://apm-server:8200
            - ELASTIC_APM_ENVIRONMENT=localhost
            - ELASTIC_APM_SERVICE_VERSION=1.0
